<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Airbnb.Audit.Domain\Airbnb.Audit.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Mapster.DependencyInjection" Version="10.1.0-pre02" />
    </ItemGroup>

</Project>
