services:
  # RabbitMQ
  airbnb.broker.rabbitmq:
    container_name: "airbnb.broker.rabbitmq"
    image: rabbitmq:4.0-management
    ports:
      - "2100:5672"  # Producers/Consumers
      - "2101:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"
  
  # Application
  airbnb.sqlserver:
    container_name: "airbnb.sqlserver"
    image: mcr.microsoft.com/mssql/server:2025-latest
    ports:
      - "2000:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${APPLICATION_MSSQL_SA_PASSWORD}
    volumes:
      - "mssql_data:/var/opt/mssql"

  airbnb.api:
    container_name: "airbnb.api"
    build:
      context: "."
      dockerfile: "Monolith/Airbnb.API/Dockerfile"
    ports:
      - "3000:8080"
    environment:
      JWT__Key: ${APPLICATION_JWT_KEY}
      JWT__Issuer: ${APPLICATION_JWT_ISSUER}
      JWT__Audience: ${APPLICATION_JWT_Audience}
      JWT__ExpirationMinutes: ${APPLICATION_JWT_EXPIRATION_MINUTES}
      ConnectionStrings__DefaultConnection: ${APPLICATION_DB_CONNECTION_STRING}
      DefaultUserOptions__DefaultPassword: ${APPLICATION_DEFAULT_USER_PASSWORD}
      
      RabbitMq__HostName: ${RABBITMQ_HOSTNAME}
      RabbitMq__Port: ${RABBITMQ_PORT}
      RabbitMq__UserName: ${RABBITMQ_USER}
      RabbitMq__Password: ${RABBITMQ_PASSWORD}
      RabbitMq__Exchange: ${RABBITMQ_EXCHANGE}
      RabbitMq__Queue: ${RABBITMQ_AUDIT_QUEUE}
      RabbitMq__ClientProvidedName: "user-service"
    depends_on:
      airbnb.sqlserver:
        condition: service_started
      airbnb.broker.rabbitmq:
        condition: service_healthy
    
    
  # Audit
  airbnb.audit.mongodb:
    container_name: "airbnb.audit.mongodb"
    image: mongo:8.0.4
    ports:
      - "2001:27017"
    environment:
      MONGO_INITDB_DATABASE: airbnb-audit-db
      MONGO_INITDB_ROOT_USERNAME: ${AUDIT_MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${AUDIT_MONGODB_PASSWORD}
    volumes:
      - "mongodb_data:/data/db"
    restart: unless-stopped
      
  airbnb.audit.api:
    container_name: "airbnb.audit.api"
    build:
      context: "."
      dockerfile: "Audit/Airbnb.Audit.API/Dockerfile"
    ports:
      - "3001:8080"
    environment:
      MongoDB__DatabaseName: ${AUDIT_MONGODB_DATABASE_NAME}
      MongoDB__UserAuditsCollectionName: ${AUDIT_MONGODB_USER_AUDITS_COLLECTION_NAME}
      ConnectionStrings__MongoDB: ${AUDIT_MONGODB_DB_CONNECTION_STRING}
      
      RabbitMq__HostName: ${RABBITMQ_HOSTNAME}
      RabbitMq__Port: ${RABBITMQ_PORT}
      RabbitMq__UserName: ${RABBITMQ_USER}
      RabbitMq__Password: ${RABBITMQ_PASSWORD}
      RabbitMq__Exchange: ${RABBITMQ_EXCHANGE}
      RabbitMq__Queue: ${RABBITMQ_AUDIT_QUEUE}
      RabbitMq__ClientProvidedName: "audit_service"
    depends_on:
      airbnb.audit.mongodb:
        condition: service_started
      airbnb.broker.rabbitmq:
        condition: service_healthy
    
  
volumes:
  rabbitmq_data:
  mssql_data:
  mongodb_data: