<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Airbnb.Domain\Airbnb.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
      <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="10.0.10" />
      <PackageReference Include="Microsoft.Extensions.Identity.Stores" Version="10.0.10" />
      <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.2" />
    </ItemGroup>

</Project>
